name: Nightly DAST

on:
  schedule:
    - cron: "0 2 * * *" # Runs every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  zap-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "https://in5nite-e8d9b0g5cad9hrbg.southeastasia-01.azurewebsites.net/"
          allow_issue_writing: false
          fail_action: false
          cmd_options: >
            -J report_json.json
            -r report_html.html
